[2024-04-23T15:17:26.950+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-04-23T15:17:22.531276+00:00 [queued]>
[2024-04-23T15:17:26.960+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-04-23T15:17:22.531276+00:00 [queued]>
[2024-04-23T15:17:26.961+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T15:17:26.995+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): create_tables> on 2024-04-23 15:17:22.531276+00:00
[2024-04-23T15:17:27.015+0000] {standard_task_runner.py:60} INFO - Started process 4177 to run task
[2024-04-23T15:17:27.021+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_tables', 'manual__2024-04-23T15:17:22.531276+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmprr1auuqy']
[2024-04-23T15:17:27.039+0000] {standard_task_runner.py:88} INFO - Job 142: Subtask create_tables
[2024-04-23T15:17:27.139+0000] {task_command.py:423} INFO - Running <TaskInstance: etl.create_tables manual__2024-04-23T15:17:22.531276+00:00 [running]> on host e2cec6840fb2
[2024-04-23T15:17:27.291+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T15:17:22.531276+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T15:17:22.531276+00:00'
[2024-04-23T15:17:27.340+0000] {base.py:83} INFO - Using connection ID 'my_postgres_conn' for task execution.
[2024-04-23T15:17:27.671+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-23T15:17:27.680+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_tables, execution_date=20240423T151722, start_date=20240423T151726, end_date=20240423T151727
[2024-04-23T15:17:27.742+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T15:17:27.764+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
