[2024-04-24T01:33:11.674+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.get_files scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T01:33:11.719+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.get_files scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T01:33:11.719+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-24T01:33:11.794+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_files> on 2024-04-23 00:00:00+00:00
[2024-04-24T01:33:11.818+0000] {standard_task_runner.py:60} INFO - Started process 357 to run task
[2024-04-24T01:33:11.822+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl', 'get_files', 'scheduled__2024-04-23T00:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpzcsxidmq']
[2024-04-24T01:33:11.852+0000] {standard_task_runner.py:88} INFO - Job 147: Subtask get_files
[2024-04-24T01:33:12.003+0000] {task_command.py:423} INFO - Running <TaskInstance: etl.get_files scheduled__2024-04-23T00:00:00+00:00 [running]> on host e2cec6840fb2
[2024-04-24T01:33:12.228+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='get_files' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-23T00:00:00+00:00'
[2024-04-24T01:33:12.234+0000] {logging_mixin.py:188} INFO - 3 files found in /opt/***/dags/data
[2024-04-24T01:33:12.236+0000] {python.py:202} INFO - Done. Returned value was: ['/opt/***/dags/data/github_events_01.json', '/opt/***/dags/data/github_events_03.json', '/opt/***/dags/data/github_events_02.json']
[2024-04-24T01:33:12.284+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl, task_id=get_files, execution_date=20240423T000000, start_date=20240424T013311, end_date=20240424T013312
[2024-04-24T01:33:12.384+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-24T01:33:12.528+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
